package com.github.wanggit.mybatis.cache.enhancement.dao.mapper;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Configuration;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.ConfigurationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int countByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int insert(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int insertSelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    List<Configuration> selectByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    Configuration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Configuration record, @Param("example") ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Configuration record, @Param("example") ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Configuration record);
}