package com.github.wanggit.mybatis.cache.enhancement.service.impl;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Account;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.AccountExample;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import com.github.wanggit.mybatis.cache.enhancement.dao.mapper.AccountMapper;
import com.github.wanggit.mybatis.cache.enhancement.service.AccountService;


@Service 
@Transactional(rollbackFor = Exception.class) 
public class AccountServiceImpl implements AccountService {

	@Autowired
	private AccountMapper accountMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int countByExample(AccountExample example){
		return accountMapper.countByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int deleteByExample(AccountExample example){
		return accountMapper.deleteByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int deleteByPrimaryKey(Integer id){
		return accountMapper.deleteByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int insert(Account record){
		return accountMapper.insert(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int insertSelective(Account record){
		return accountMapper.insertSelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public List<Account> selectByExample(AccountExample example){
		return accountMapper.selectByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public Account selectByPrimaryKey(Integer id){
		return accountMapper.selectByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int updateByExampleSelective(Account record,  AccountExample example){
		return accountMapper.updateByExampleSelective(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int updateByExample(Account record,  AccountExample example){
		return accountMapper.updateByExample(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int updateByPrimaryKeySelective(Account record){
		return accountMapper.updateByPrimaryKeySelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
	public int updateByPrimaryKey(Account record){
		return accountMapper.updateByPrimaryKey(record);
	}
}