package com.github.wanggit.mybatis.cache.enhancement.service.impl;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Group;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.GroupExample;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import com.github.wanggit.mybatis.cache.enhancement.dao.mapper.GroupMapper;
import com.github.wanggit.mybatis.cache.enhancement.service.GroupService;


@Service 
@Transactional(rollbackFor = Exception.class) 
public class GroupServiceImpl implements GroupService {

	@Autowired
	private GroupMapper groupMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int countByExample(GroupExample example){
		return groupMapper.countByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int deleteByExample(GroupExample example){
		return groupMapper.deleteByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int deleteByPrimaryKey(Integer id){
		return groupMapper.deleteByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int insert(Group record){
		return groupMapper.insert(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int insertSelective(Group record){
		return groupMapper.insertSelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public List<Group> selectByExample(GroupExample example){
		return groupMapper.selectByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public Group selectByPrimaryKey(Integer id){
		return groupMapper.selectByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int updateByExampleSelective(Group record,  GroupExample example){
		return groupMapper.updateByExampleSelective(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int updateByExample(Group record,  GroupExample example){
		return groupMapper.updateByExample(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int updateByPrimaryKeySelective(Group record){
		return groupMapper.updateByPrimaryKeySelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
	public int updateByPrimaryKey(Group record){
		return groupMapper.updateByPrimaryKey(record);
	}
}