package com.github.wanggit.mybatis.cache.enhancement.service.impl;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Project;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.ProjectExample;
import java.util.List;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import com.github.wanggit.mybatis.cache.enhancement.dao.mapper.ProjectMapper;
import com.github.wanggit.mybatis.cache.enhancement.service.ProjectService;


@Service 
@Transactional(rollbackFor = Exception.class) 
public class ProjectServiceImpl implements ProjectService {

	@Autowired
	private ProjectMapper projectMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int countByExample(ProjectExample example){
		return projectMapper.countByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int deleteByExample(ProjectExample example){
		return projectMapper.deleteByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int deleteByPrimaryKey(Integer id){
		return projectMapper.deleteByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int insert(Project record){
		return projectMapper.insert(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int insertSelective(Project record){
		return projectMapper.insertSelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public List<Project> selectByExample(ProjectExample example){
		return projectMapper.selectByExample(example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public Project selectByPrimaryKey(Integer id){
		return projectMapper.selectByPrimaryKey(id);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int updateByExampleSelective(Project record,  ProjectExample example){
		return projectMapper.updateByExampleSelective(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int updateByExample(Project record,  ProjectExample example){
		return projectMapper.updateByExample(record, example);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int updateByPrimaryKeySelective(Project record){
		return projectMapper.updateByPrimaryKeySelective(record);
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
	public int updateByPrimaryKey(Project record){
		return projectMapper.updateByPrimaryKey(record);
	}
}