package com.github.wanggit.mybatis.cache.enhancement.service;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Account;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.AccountExample;
import java.util.List;


public interface AccountService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Account record,  AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int updateByExample(Account record,  AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Account record);
}