package com.github.wanggit.mybatis.cache.enhancement.service;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Configuration;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.ConfigurationExample;
import java.util.List;


public interface ConfigurationService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int countByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int insert(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int insertSelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    List<Configuration> selectByExample(ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    Configuration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Configuration record,  ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByExample(Configuration record,  ConfigurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_configuration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Configuration record);
}