package com.github.wanggit.mybatis.cache.enhancement.service;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Group;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.GroupExample;
import java.util.List;


public interface GroupService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int countByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int deleteByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    List<Group> selectByExample(GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Group record,  GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int updateByExample(Group record,  GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Group record);
}