package com.github.wanggit.mybatis.cache.enhancement.service;

import com.github.wanggit.mybatis.cache.enhancement.dao.entity.Project;
import com.github.wanggit.mybatis.cache.enhancement.dao.entity.ProjectExample;
import java.util.List;


public interface ProjectService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Project record,  ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int updateByExample(Project record,  ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cc_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project record);
}